MMCs/blueprints/auth.py
# -*- coding: utf-8 -*-

from flask import Blueprint, flash, redirect, render_template, url_for
from flask_babel import _
from flask_login import (confirm_login, current_user, login_fresh,
                         login_required, login_user, logout_user)

from MMCs.forms import LoginForm
from MMCs.models import User
from MMCs.utils import log_user, redirect_back

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('front.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.validate_password(form.password.data):
            if login_user(user, form.remember_me.data):
                content = render_template('logs/auth/login.txt')
                log_user(content)

                flash(_('Login success.'), 'info')
                return redirect_back()
        else:
            flash(_('Invalid username or password.'), 'warning')

    return render_template('auth/login.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    content = render_template('logs/auth/logout.txt')
    log_user(content)

    logout_user()
    flash(_('Logout success.'), 'info')

    return redirect(url_for('front.index'))


@auth_bp.route('/re-authenticate', methods=['GET', 'POST'])
@login_required
def re_authenticate():
    if login_fresh():
        return redirect(url_for('front.index'))

    form = LoginForm()
    if form.validate_on_submit() and current_user.validate_password(form.password.data):
        confirm_login()

        content = render_template('logs/auth/login.txt')
        log_user(content)

        return redirect_back()
    return render_template('auth/login.html', form=form)

MMCs/blueprints/backstage.py
# -*- coding: utf-8 -*-

import os

from flask import (Blueprint, abort, current_app, flash, render_template,
                   send_file)
from flask_babel import _
from flask_login import current_user, fresh_login_required, login_required

from MMCs.extensions import db
from MMCs.forms import ChangePasswordForm, ChangeUsernameForm, EditProfileForm
from MMCs.models import Competition
from MMCs.utils import log_user, redirect_back

backstage_bp = Blueprint('backstage', __name__)


@backstage_bp.route('/settings/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.realname = form.realname.data
        current_user.remark = form.remark.data
        db.session.commit()

        content = render_template('logs/settings/edit_profile.txt')
        log_user(content)

        flash(_('Profile updated.'), 'success')
        return redirect_back()

    form.realname.data = current_user.realname
    form.remark.data = current_user.remark

    return render_template('backstage/settings/edit_profile.html', form=form)


@backstage_bp.route('/settings/change-username', methods=['GET', 'POST'])
@login_required
@fresh_login_required
def change_username():
    form = ChangeUsernameForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        db.session.commit()

        content = render_template('logs/settings/change_username.txt')
        log_user(content)

        flash(_('Username updated.'), 'success')
        return redirect_back()

    return render_template('backstage/settings/change_username.html', form=form)


@backstage_bp.route('/settings/change-password', methods=['GET', 'POST'])
@fresh_login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        content = render_template('logs/settings/change_password.txt')
        log_user(content)

        if current_user.validate_password(form.old_password.data):
            current_user.set_password(form.password.data)
            db.session.commit()

            flash(_('Password updated.'), 'success')
            return redirect_back()
        else:
            flash(_('Old password is incorrect.'), 'warning')

    return render_template('backstage/settings/change_password.html', form=form)


@backstage_bp.route('/solution/<path:filename>')
@login_required
def get_solution(filename):
    content = render_template('logs/download.txt')
    log_user(content)

    if Competition.is_start():
        path = os.path.join(
            current_app.config['SOLUTION_SAVE_PATH'], filename)
        if os.path.exists(path):
            return send_file(path, as_attachment=True)
        else:
            abort(404)
    else:
        abort(403)

MMCs/blueprints/front.py
# -*- coding: utf-8 -*-

from flask import (Blueprint, abort, current_app, flash, make_response,
                   redirect, render_template, url_for)
from flask_babel import _
from flask_login import current_user

from MMCs.extensions import cache, db
from MMCs.utils import redirect_back

front_bp = Blueprint('front', __name__)


@front_bp.route('/')
def index():
    if current_user.is_authenticated:
        if current_user.is_root:
            return redirect(url_for('root.index'))
        elif current_user.is_admin:
            return redirect(url_for('admin.index'))
        elif current_user.is_teacher:
            return redirect(url_for('teacher.index'))
    return render_template('front/index.html')


@front_bp.route('/about')
@cache.cached(timeout=10)
def about():
    return render_template('front/about.html')


@front_bp.route('/set-locale/<locale>')
def set_locale(locale):
    if locale not in current_app.config['MMCS_LOCALES']:
        abort(404)

    response = make_response(redirect_back())
    response.set_cookie('locale', locale, max_age=60 * 60 * 24 * 30)

    if current_user.is_authenticated:
        current_user.locale = locale
        db.session.commit()

    flash(_('Setting updated.'), 'success')

    return response

MMCs/templates/base.html
<!--
    __  _____  _________    
   /  |/  /  |/  / ____/____
  / /|_/ / /|_/ / /   / ___/
 / /  / / /  / / /___(__  ) 
/_/  /_/_/  /_/\____/____/  
-->
{% from 'macros.html' import render_nav_item %}
{% from 'macros.html' import link_field %}
<!DOCTYPE html>
<html lang="zh">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %} · MMCs</title>
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
    {% block styles %}
        {{ bootstrap.load_css() }}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flat-ui/2.3.0/css/flat-ui.min.css"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" />
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% endblock styles %}
</head>

<body>
{% block navbar %}
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('front.index') }}">
                <img src="{{ url_for('static', filename='navbar-brand.ico') }}" alt="MMCs" width="80">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="navbar-nav mr-auto">
                    {{ render_nav_item('front.index', _('Home'), "oi oi-home") }}
                    {{ render_nav_item('front.about', _('About'), "oi oi-bookmark") }}
                </div>
                {% if not current_user.is_authenticated %}
                    <div class="navbar-nav nav-item ml-auto">
                        <a class="btn btn-outline-success" href="{{ url_for('auth.login') }}">
                            {{ _('Welcome to MMCs') }}
                        </a>
                    </div>
                {% endif %}
                <div class="dropdown nav-item navbar-nav">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown">
                        <span class="oi oi-globe"></span> {{ _('Language') }}
                    </a>
                    <div class="dropdown-menu" role="menu">
                        <a class="dropdown-item"
                           href="{{ url_for('front.set_locale', locale='zh_Hans_CN') }}">简体中文</a>
                        <a class="dropdown-item"
                           href="{{ url_for('front.set_locale', locale='en_US') }}">English</a>
                    </div>
                </div>
                {% if current_user.is_authenticated %}
                    <div class="dropdown nav-item navbar-nav">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown">
                            <span class="oi oi-person"></span>
                        </a>
                        <div class="dropdown-menu" role="menu">
                            <h6 class="dropdown-header">{{ _('Logged in as') }} {{ current_user.realname }}</h6>
                            <a class="dropdown-item" href="{{ url_for('backstage.edit_profile') }}">
                                <span class="oi oi-cog"></span> {{ _('Settings') }}</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('auth.logout', next=request.full_path) }}">
                                <span class="oi oi-account-logout"></span> {{ _('Logout') }}</a>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </nav>
{% endblock navbar %}

<main>
    <div class="container">
        {% for message in get_flashed_messages(with_categories=True) %}
            <div class="alert alert-{{ message[0] }}">
                <button type="button" class="close" data-dismiss="alert">
                    <span class="oi oi-delete"></span>
                </button>
                {{ message[1] }}
            </div>
        {% endfor %}

        {% block content %}
        {% endblock content %}
    </div>

    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <p class="float-left">
                        <small> &copy; {{ current_year() }}
                            <a href="http://sxjm.ncst.edu.cn"
                               title="{{ _('North China University of Science and Technology University Mathematical Modeling Association') }}"
                               data-toggle="tooltip">
                                NCUST-MMA /</a>
                            {{ link_field("Zero", "https://github.com/Zeroto521", "Written by Zeroto521") }}
                        </small>
                    </p>
                </div>
                <div class="col-6">
                    <p class="float-right">
                        <small>
                            <a title="{{ _('North China University of Science and Technology University Mathematical Modeling Competition system') }}"
                               data-toggle="tooltip">{{ _('Mathematical Modeling Competition system') }}</a>
                        </small>
                    </p>
                </div>
            </div>
        </div>
    </footer>
</main>

{% block scripts %}
    {{ bootstrap.load_js() }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flat-ui/2.3.0/js/flat-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flat-ui/2.3.0/js/vendor/respond.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $("[data-toggle='tooltip']").tooltip();
        });
    </script>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
{% endblock scripts %}
</body>

</html>

MMCs/templates/errors.html
{% extends 'base.html' %}

{% block title %}{{ code }} Error{% endblock %}

{% block content %}
    <div class="row justify-content-md-center">
        <div class="card w-50">
            <img class="card-img-top img-fluid" src="{{ url_for('static', filename='images/error.jpg') }}" alt="error">
            <div class="card-body">
                <h5 class="card-title">{{ code }} Error</h5>
                <p class="card-text">{{ info }}</p>
            </div>
            <div class="card-footer">
                <div class="float-right">
                    <a class="btn btn-primary" href="{{ url_for('front.index') }}">{{ _('Back Home') }}</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

MMCs/templates/macros.html
{% macro link_field(link_name, link_url, link_title) %}
    <a href="{{ link_url }}" title="{{ link_title }}" target="_blank" data-toggle="tooltip">{{ link_name }}</a>
{% endmacro %}

{% macro render_nav_item(endpoint, text, icon='', badge='', disable=False, use_li=False) %}
    {% if use_li %}
        <li class="nav-item">
    {% endif %}

<a class="{% if not use_li %}nav-item{% endif %} nav-link {% if request.endpoint and request.endpoint == endpoint %}active{% endif %} {% if disable %}disabled{% endif %}"
   href="{{ url_for(endpoint, **kwargs) }}">
    {% if icon %}<span class="{{ icon }}"></span> {% endif %}{{ text }}{% if badge %}
    <span class="badge badge-light">{{ badge }}</span>{% endif %}
</a>

{% if use_li %}
    </li>
{% endif %}
{% endmacro %}