MMCs/blueprints/root.py
# -*- coding: utf-8 -*-

import os
from uuid import uuid4

from flask import (Blueprint, current_app, flash, redirect, render_template,
                   request, send_file, url_for)
from flask_babel import _
from flask_login import fresh_login_required, login_required

from MMCs.decorators import root_required
from MMCs.extensions import db
from MMCs.forms import (AboutEditForm, AboutImageUploadForm,
                        ChangeUsernameForm, CompetitionNameForm,
                        CompetitionSettingForm, DownloadLogForm,
                        EditProfileForm, ErrorImageUploadForm,
                        IndexImageUploadForm, NoticeEditForm, RegisterForm,
                        RootChangePasswordForm)
from MMCs.models import Competition, User
from MMCs.settings import basedir
from MMCs.utils import (download_solution_score, download_teacher_result,
                        download_user_operation, flash_errors, log_user,
                        read_localfile, redirect_back, write_localfile,
                        zip2here)

root_bp = Blueprint('root', __name__)


@root_bp.route('/')
@root_required
@login_required
def index():
    return redirect(url_for('.manage_competition'))


@root_bp.route('/competition')
@root_required
@login_required
def manage_competition():
    return redirect(url_for('root.behavior'))


@root_bp.route('/competition/behavior')
@root_required
@login_required
def behavior():
    form = CompetitionNameForm()
    return render_template(
        'backstage/root/manage_competition/behavior.html', form=form)


@root_bp.route('/competition/history')
@root_required
@login_required
def history():
    page = request.args.get('page', 1, type=int)
    pagination = Competition.query.order_by(
        Competition.id.desc()).paginate(page, current_app.config['COMPETITION_PER_PAGE'])

    return render_template(
        'backstage/root/manage_competition/history.html',
        pagination=pagination, page=page)


@root_bp.route('/competition/notice', methods=['GET', 'POST'])
@fresh_login_required
@root_required
@login_required
def notice():
    form = NoticeEditForm()
    path = os.path.join(
        basedir, current_app.name, current_app.template_folder, 'showing/notice.html')
    if form.validate_on_submit():
        content = render_template('logs/root/competition/notice.txt')
        log_user(content)

        write_localfile(path, form.notice.data)
        flash(_('Setting updated.'), 'success')
        return redirect_back()
    form.notice.data = read_localfile(path)

    return render_template(
        'backstage/root/manage_competition/notice.html', form=form)


@root_bp.route('/competition/settings', methods=['GET', 'POST'])
@fresh_login_required
@root_required
@login_required
def competition_settings():
    form = CompetitionSettingForm()
    if form.validate_on_submit():
        content = render_template('logs/root/competition/setting.txt')
        log_user(content)

        current_app.config['SOLUTION_TASK_NUMBER'] = form.solution_task_number.data
        current_app.config['USER_PER_PAGE'] = form.user_per_page.data
        current_app.config['SOLUTION_PER_PAGE'] = form.solution_per_page.data
        current_app.config['COMPETITION_PER_PAGE'] = form.competition_per_page.data
        current_app.config['DROPZONE_MAX_FILES'] = form.dropzone_max_files.data

    form.solution_task_number.data = current_app.config['SOLUTION_TASK_NUMBER']
    form.user_per_page.data = current_app.config['USER_PER_PAGE']
    form.solution_per_page.data = current_app.config['SOLUTION_PER_PAGE']
    form.competition_per_page.data = current_app.config['COMPETITION_PER_PAGE']
    form.dropzone_max_files.data = current_app.config['DROPZONE_MAX_FILES']

    return render_template(
        'backstage/root/manage_competition/notice.html', form=form)


@root_bp.route('/competition/behavior/start', methods=['POST'])
@fresh_login_required
@root_required
@login_required
def start_competition():
    form = CompetitionNameForm()
    if form.validate_on_submit():
        content = render_template('logs/root/competition/start.txt')
        log_user(content)

        com = Competition(name=form.name.data, flag=True)
        db.session.add(com)
        db.session.commit()
        flash(_('A new competition start now.'), 'success')

    flash_errors(form)

    return redirect_back()


@root_bp.route('/competition/behavior/switch', methods=['POST'])
@fresh_login_required
@root_required
@login_required
def switch_state():
    com = Competition.current_competition()
    if com:
        if com.is_start():
            com.flag = False
            db.session.commit()

            content = render_template('logs/root/competition/stop.txt')
            log_user(content)

            flash(_('Competition stopped.'), 'success')
        else:
            com.flag = True
            db.session.commit()

            content = render_template('logs/root/competition/start.txt')
            log_user(content)

            flash(_('Competition continued.'), 'success')
    else:
        flash(_('Please start new competition before do it.'), 'warning')

    return redirect_back()


@root_bp.route('/personnel')
@root_required
@login_required
def manage_personnel():
    return redirect(url_for('.personnel_list'))


@root_bp.route('/personnel/list')
@root_required
@login_required
def personnel_list():
    page = request.args.get('page', 1, type=int)
    pagination = User.query.order_by(
        User.id.desc()).paginate(page, current_app.config['USER_PER_PAGE'])

    return render_template(
        'backstage/root/manage_personnel/personnel_list.html',
        pagination=pagination, page=page)


@root_bp.route('/personnel/list/change-password/<int:user_id>', methods=['GET', 'POST'])
@fresh_login_required
@root_required
@login_required
def change_password(user_id):
    form = RootChangePasswordForm()
    if form.validate_on_submit():
        content = render_template('logs/root/personnel/change_password.txt')
        log_user(content)

        user = User.query.get_or_404(user_id)
        user.set_password(form.password.data)
        db.session.commit()

        flash(_('Password updated.'), 'success')
        return redirect(url_for('.personnel_list'))

    return render_template(
        'backstage/root/manage_personnel/personnel_edit.html', form=form)


@root_bp.route('/personnel/list/edit-profile/<int:user_id>', methods=['GET', 'POST'])
@fresh_login_required
@root_required
@login_required
def edit_profile(user_id):
    user = User.query.get_or_404(user_id)
    form = EditProfileForm()
    if form.validate_on_submit():
        content = render_template('logs/root/personnel/edit.txt')
        log_user(content)

        user.realname = form.realname.data
        user.remark = form.remark.data
        db.session.commit()

        flash(_('Profile updated.'), 'success')
        return redirect(url_for('.personnel_list'))

    form.realname.data = user.realname
    form.remark.data = user.remark

    return render_template(
        'backstage/root/manage_personnel/personnel_edit.html', form=form)


@root_bp.route('/personnel/list/change-username/<int:user_id>', methods=['GET', 'POST'])
@fresh_login_required
@root_required
@login_required
def change_username(user_id):
    user = User.query.get_or_404(user_id)
    form = ChangeUsernameForm()
    if form.validate_on_submit():
        content = render_template('logs/root/personnel/change_username.txt')
        log_user(content)

        user.username = form.username.data
        db.session.commit()

        flash(_('Username updated.'), 'success')
        return redirect(url_for('.personnel_list'))

    form.username.data = user.username
    form.username2.data = user.username

    return render_template(
        'backstage/root/manage_personnel/personnel_edit.html', form=form)


@root_bp.route('/personnel/register', methods=['GET', 'POST'])
@fresh_login_required
@root_required
@login_required
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        content = render_template('logs/root/personnel/register.txt')
        log_user(content)

        user = User(
            username=form.username.data,
            realname=form.realname.data,
            permission=form.permission.data,
            remark=form.remark.data
        )
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash(_('Account registered.'), 'success')
        return redirect_back()

    return render_template('backstage/root/manage_personnel/register.html', form=form)


@root_bp.route('/delete/user/<int:user_id>', methods=['POST'])
@fresh_login_required
@root_required
@login_required
def delete_user(user_id):
    content = render_template('logs/root/personnel/delete.txt')
    log_user(content)

    user = User.query.get_or_404(user_id)
    db.session.delete(user)
    db.session.commit()

    flash(_('User deleted.'), 'info')
    return redirect_back()


@root_bp.route('/score/download/<int:competition_id>/teacher', methods=['POST'])
@fresh_login_required
@root_required
@login_required
def download_teacher(competition_id):
    content = render_template('logs/root/competition/history.txt')
    log_user(content)

    com = Competition.query.get_or_404(competition_id)
    if com.tasks:
        zfile = download_teacher_result(competition_id)

        flash(_('The result file is already downloaded.'), 'success')
        return send_file(zfile, as_attachment=True)
    else:
        flash(_('No task.'), 'warning')
        return redirect_back()


@root_bp.route('/score/download/<int:competition_id>/result', methods=['POST'])
@fresh_login_required
@root_required
@login_required
def download_result(competition_id):
    content = render_template('logs/root/competition/history.txt')
    log_user(content)

    com = Competition.query.get_or_404(competition_id)
    if com.solutions:
        zfile = download_solution_score(competition_id)

MMCs/templates/backstage/root/manage_competition/base.html
{% extends 'backstage/root/base.html' %}

{% block title %}Competition{% endblock %}

{% block setting_content %}
    <div class="card w-100">
        <div class="card-header">
            <div class="nav nav-tabs card-header-tabs" role="tablist">
                {{ render_nav_item("root.behavior", _("Competition")) }}
                {{ render_nav_item("root.history", _("History")) }}
                {{ render_nav_item("root.notice", _("Notice")) }}
                {{ render_nav_item("root.competition_settings", _("Settings")) }}
            </div>
        </div>
        <div class="card-body">
            {% block competition_content %}
            {% endblock %}
        </div>
    </div>
{% endblock %}

MMCs/templates/backstage/root/manage_competition/behavior.html
{% extends 'backstage/root/manage_competition/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block competition_content %}
    <div class="btn-group btn-group-vertical btn-block" role="group">
        <button class="btn btn-danger" data-toggle="modal" data-target="#confirm-start">
            <span class="oi oi-play-circle"></span> {{ _("Start") }}
        </button>
        {% if is_start() %}
            <button class="btn btn-secondary" data-toggle="modal" data-target="#confirm-stop"
                    data-href="{{ url_for('root.switch_state') }}">
                <span class="oi oi-media-pause"></span> {{ _("Stop") }}
            </button>
        {% else %}
            <button class="btn btn-primary" data-toggle="modal" data-target="#confirm-continue"
                    data-href="{{ url_for('root.switch_state') }}">
                <span class="oi oi-media-play"></span> {{ _("Continue") }}
            </button>
        {% endif %}
    </div>
    <!-- start modal -->
    <div class="modal fade" id="confirm-start" tabindex="-1" role="dialog" aria-labelledby="confirmStartModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmStartModalLabel">
                        {{ _("Are you sure you want to start up a new competition?") }}
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span class="oi oi-delete"></span>
                    </button>
                </div>
                <form action="{{ url_for('root.start_competition') }}" method="post">
                    <div class="modal-body">
                        {{ form.csrf_token }}
                        {{ form.name.label(class="form-control-label") }}
                        {{ form.name(class="form-control") }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">
                            <span class="oi oi-action-undo"></span> {{ _("Cancel") }}
                        </button>
                        <button class="btn btn-danger btn-confirm" id="submit" name="submit" type="submit">
                            <span class="oi oi-check"></span> {{ _("Confirm") }}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- stop modal -->
    <div class="modal fade" id="confirm-stop" tabindex="-1" role="dialog" aria-labelledby="confirmStopModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmStopModalLabel"> {{ _("Stop Confirm") }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span class="oi oi-delete"></span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>{{ _("Are you sure you want to stop this competition?") }}</p>
                </div>
                <div class="modal-footer">
                    <form class="stop-form" method="post">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                        <button type="button" class="btn btn-default" data-dismiss="modal">
                            <span class="oi oi-action-undo"></span> {{ _("Cancel") }}
                        </button>
                        <button class="btn btn-danger btn-confirm" type="submit">
                            <span class="oi oi-check"></span> {{ _("Confirm") }}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- continue modal -->
    <div class="modal fade" id="confirm-continue" tabindex="-1" role="dialog"
         aria-labelledby="confirmContinueModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmContinueModalLabel">{{ _("Continue Confirm") }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span class="oi oi-delete"></span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>{{ _("Are you sure you want to continue this competition?") }}</p>
                </div>
                <div class="modal-footer">
                    <form class="continue-form" method="post">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                        <button type="button" class="btn btn-default" data-dismiss="modal">
                            <span class="oi oi-action-undo"></span> {{ _("Cancel") }}
                        </button>
                        <button class="btn btn-danger btn-confirm" type="submit">
                            <span class="oi oi-check"></span> {{ _("Confirm") }}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

MMCs/templates/backstage/root/manage_competition/history.html
{% extends 'backstage/root/manage_competition/base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block competition_content %}
    <h4>
        Competitions
        <small class="text-muted">{{ pagination.total|default(0) }}</small>
    </h4>

    <div>
        <div class="table-responsive">
            <table class="table table-striped table-hover table-sm">
                <thead>
                <tr class="text-center">
                    <th>#</th>
                    <th>{{ _("Competition name") }}</th>
                    <th>{{ _("Date") }}</th>
                    <th>{{ _("Actions") }}</th>
                </tr>
                </thead>
                {% for com in pagination.items %}
                    <tr>
                        <td class="text-center">
                            {{ pagination.total - (config['COMPETITION_PER_PAGE'] * (page - 1) + loop.index) + 1 }}
                        </td>
                        <td class="text-center">{{ com.name }}</td>
                        <td class="text-center">{{ com.date }}</td>
                        <td class="text-center">
                            <div class="btn-group dropleft">
                                <button class="btn btn-sm btn-info dropdown-toggle" type="button"
                                        id="dropdownMenuButton"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="oi oi-cloud-download"></span> {{ _("Download") }}
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <form role="form"
                                          action="{{ url_for('root.download_teacher', competition_id=com.id) }}"
                                          method="post">
                                        <input type="hidden" id="csrf_token" name="csrf_token"
                                               value="{{ csrf_token() }}"/>
                                        <button class="dropdown-item">
                                            <span class="oi oi-data-transfer-download"></span> {{ _("Download all teachers result") }}
                                        </button>
                                    </form>
                                    <form role="form"
                                          action="{{ url_for('root.download_teacher', competition_id=com.id) }}"
                                          method="post">
                                        <input type="hidden" id="csrf_token" name="csrf_token"
                                               value="{{ csrf_token() }}"/>
                                        <button class="dropdown-item">
                                            <span class="oi oi-data-transfer-download"></span> {{ _("Download the final result") }}
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="page-footer">
            {{ render_pagination(pagination) }}
        </div>
    </div>
{% endblock %}

MMCs/templates/backstage/root/manage_competition/notice.html
{% extends 'backstage/root/manage_competition/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block competition_content %}
    {{ render_form(form) }}
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ ckeditor.load() }}
{% endblock %}

MMCs/templates/backstage/root/manage_competition/settings.html
{% extends 'backstage/root/manage_competition/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block competition_content %}
    {{ render_form(form) }}
{% endblock %}