MMCs/blueprints/admin.py
# -*- coding: utf-8 -*-

import os

from flask import (Blueprint, current_app, flash, redirect, render_template,
                   request, send_file, url_for)
from flask_babel import _
from flask_login import fresh_login_required, login_required

from MMCs.decorators import admin_required
from MMCs.extensions import db
from MMCs.forms import ButtonAddForm, ButtonCheckForm
from MMCs.models import Competition, Solution, Task, User
from MMCs.utils import (allowed_file, check_filename, download_solution_score,
                        download_teacher_result, log_user, new_filename,
                        random_sample, redirect_back)

admin_bp = Blueprint('admin', __name__)


@admin_bp.route('/')
@admin_required
@login_required
def index():
    com = Competition.current_competition()
    if com and com.is_start():
        tasks = com.tasks
        task_all = task_finished = 0
        if tasks:
            task_all = len(tasks)
            task_finished = len([
                task for task in tasks if task.score is not None])

        return render_template(
            'backstage/admin/overview.html', task_finished=task_finished, task_all=task_all)

    return render_template('backstage/admin/overview.html')


@admin_bp.route('/solution')
@admin_required
@login_required
def manage_solution():
    return redirect(url_for('admin.solution_list'))


@admin_bp.route('/solution/list')
@admin_required
@login_required
def solution_list():
    com = Competition.current_competition()
    if com:
        page = request.args.get('page', 1, type=int)
        pagination = Solution.query.filter_by(competition_id=com.id).order_by(
            Solution.id.desc()).paginate(page, current_app.config['SOLUTION_PER_PAGE'])

        form = ButtonAddForm()

        return render_template(
            'backstage/admin/manage_solution/solution_list.html',
            pagination=pagination, page=page, form=form)

    return render_template('backstage/admin/manage_solution/solution_list.html')


@admin_bp.route('/solution/upload', methods=['GET', 'POST'])
@fresh_login_required
@admin_required
@login_required
def upload():
    if request.method == 'POST' and 'file' in request.files:
        content = render_template('logs/admin/solution/upload.txt')
        log_user(content)

        if Competition.is_start():
            file = request.files.get('file')
            filename, uuid = new_filename(file.filename)
            if allowed_file(filename):
                flag, info = check_filename(filename)
                if flag:
                    path = current_app.config['SOLUTION_SAVE_PATH']
                    file.save(os.path.join(path, uuid))

                    com = Competition.current_competition()
                    solution = Solution(
                        name=filename, uuid=uuid, competition_id=com.id)
                    db.session.add(solution)
                    db.session.commit()
                else:
                    return info, 400
            else:
                ext = current_app.config['ALLOWED_SOLUTION_EXTENSIONS']
                return '{} only!'.format(', '.join(ext)), 400
        else:
            return _("Competition of current year don't start."), 403

    return render_template('backstage/admin/manage_solution/upload.html')


@admin_bp.route('/solution/delete/<int:solution_id>', methods=['POST'])
@fresh_login_required
@admin_required
@login_required
def delete_solution_task(solution_id):
    solution = Solution.query.get_or_404(solution_id)
    db.session.delete(solution)
    db.session.commit()

    content = render_template('logs/admin/solution/delete.txt')
    log_user(content)

    flash(_('Solution deleted.'), 'info')
    return redirect_back()


@admin_bp.route('/task')
@admin_required
@login_required
def manage_task():
    return redirect(url_for('admin.teacher_view'))


@admin_bp.route('/task/method', methods=['GET', 'POST'])
@admin_required
@login_required
def method():
    return render_template('backstage/admin/manage_task/method.html')


@admin_bp.route('/task/method/random', methods=['POST'])
@fresh_login_required
@admin_required
@login_required
def method_random():
    content = render_template('logs/admin/solution/random.txt')
    log_user(content)

    com = Competition.current_competition()
    Task.query.filter_by(competition_id=com.id).delete()
    db.session.commit()

    solutions = com.solutions
    if solutions:
        teachers = User.teachers()
        if teachers:
            solutions = sorted(solutions, key=lambda x: x.problem)
            for solution in solutions:
                this_problem = solution.problem
                for teacher_id in random_sample(this_problem):
                    task = Task(
                        teacher_id=teacher_id,
                        solution_id=solution.id,
                        competition_id=com.id
                    )
                    db.session.add(task)
                    try:
                        db.session.commit()
                    except:
                        db.session.rollback()

            flash(_('Randomly assigned.'), 'success')
        else:
            flash(_('Please add teacher to assign task.'), 'warning')
    else:
        flash(_('No solutions.'), 'warning')

    return redirect_back()


@admin_bp.route('/task/teacher')
@admin_required
@login_required
def teacher_view():
    page = request.args.get('page', 1, type=int)
    pagination = User.query.filter(User.permission == 'Teacher').order_by(
        User.id.desc()).paginate(page, current_app.config['USER_PER_PAGE'])

    check_form = ButtonCheckForm()
    add_form = ButtonAddForm()

    return render_template(
        'backstage/admin/manage_task/teacher_view.html',
        pagination=pagination, page=page,
        check_form=check_form, add_form=add_form)


@admin_bp.route('/task/teacher/check/<int:user_id>/tasks', methods=['GET', 'POST'])
@admin_required
@login_required
def check_user(user_id):
    content = render_template('logs/admin/task/check.txt')
    log_user(content)

    com = Competition.current_competition()
    page = request.args.get('page', 1, type=int)

    pagination = Task.query.filter(
        Task.teacher_id == user_id,
        Task.competition_id == com.id
    ).order_by(Task.id.desc()).paginate(page, current_app.config['SOLUTION_PER_PAGE'])

    return render_template(
        'backstage/admin/manage_task/check.html',
        pagination=pagination, page=page)


@admin_bp.route('/task/teacher/delete/<int:user_id>', methods=['POST'])
@fresh_login_required
@admin_required
@login_required
def delete_user_task(user_id):
    content = render_template('logs/admin/task/delete.txt')
    log_user(content)

    com = Competition.current_competition()
    Task.query.filter(
        Task.teacher_id == user_id,
        Task.competition_id == com.id).delete()
    db.session.commit()

    flash(_("All tasks of User deleted."), 'success')
    return redirect_back()


@admin_bp.route('/task/teacher/check/delete/<int:task_id>', methods=['POST'])
@fresh_login_required
@admin_required
@login_required
def method_delete_task(task_id):
    content = render_template('logs/admin/task/check.txt')
    log_user(content)

    task = Task.query.get_or_404(task_id)
    db.session.delete(task)
    db.session.commit()

    flash(_('Task deleted.'), 'success')
    return redirect_back()


@admin_bp.route('/task/teacher/check/<int:user_id>/add', methods=['GET', 'POST'])
@admin_required
@login_required
def task_add_list(user_id):
    page = request.args.get('page', 1, type=int)
    com = Competition.current_competition()
    user = User.query.get_or_404(user_id)
    solution_ids = set(
        task.solution_id for task in user.current_all_tasks)

    pagination = Solution.query.filter(
        ~Solution.id.in_(map(str, solution_ids)),
        Solution.competition_id == com.id
    ).order_by(Solution.name).paginate(page, current_app.config['SOLUTION_PER_PAGE'])

    return render_template(
        'backstage/admin/manage_task/add.html',
        pagination=pagination, page=page, user_id=user.id)


@admin_bp.route('/task/teacher/check/<int:user_id>/add/<int:solution_id>', methods=['POST'])
@fresh_login_required
@admin_required
@login_required
def task_add(user_id, solution_id):
    content = render_template('logs/admin/task/add.txt')
    log_user(content)

    com = Competition.current_competition()
    task = Task(
        teacher_id=user_id,
        solution_id=solution_id,
        competition_id=com.id
    )
    db.session.add(task)
    db.session.commit()

    flash(_('Added successed.'), 'success')
    return redirect_back()


@admin_bp.route('/task/solution')
@admin_required
@login_required
def solution_view():
    page = request.args.get('page', 1, type=int)
    com = Competition.current_competition()
    pagination = Solution.query.filter_by(competition_id=com.id).order_by(
        Solution.name).paginate(page, current_app.config['SOLUTION_PER_PAGE'])

    return render_template(
        'backstage/admin/manage_task/solution_view.html',
        pagination=pagination, page=page)


@admin_bp.route('/score')
@admin_required
@login_required
def manage_score():
    return render_template('backstage/admin/manage_score.html')


@admin_bp.route('/score/download/teacher', methods=['POST'])
@fresh_login_required
@admin_required
@login_required
def download_teacher():
    content = render_template('logs/admin/score/download.txt')
    log_user(content)

    com = Competition.current_competition()
    if com.tasks:
        zfile = download_teacher_result(com.id)

        flash(_('The result file is already downloaded.'), 'success')
        return send_file(zfile, as_attachment=True)
    else:
        flash(_('No task.'), 'warning')
        return redirect_back()


@admin_bp.route('/score/download/result', methods=['POST'])
@fresh_login_required
@admin_required
@login_required
def download_result():

MMCs/blueprints/backstage.py
# -*- coding: utf-8 -*-

import os

from flask import (Blueprint, abort, current_app, flash, render_template,
                   send_file)
from flask_babel import _
from flask_login import current_user, fresh_login_required, login_required

from MMCs.extensions import db
from MMCs.forms import ChangePasswordForm, ChangeUsernameForm, EditProfileForm
from MMCs.models import Competition
from MMCs.utils import log_user, redirect_back

backstage_bp = Blueprint('backstage', __name__)


@backstage_bp.route('/settings/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.realname = form.realname.data
        current_user.remark = form.remark.data
        db.session.commit()

        content = render_template('logs/settings/edit_profile.txt')
        log_user(content)

        flash(_('Profile updated.'), 'success')
        return redirect_back()

    form.realname.data = current_user.realname
    form.remark.data = current_user.remark

    return render_template('backstage/settings/edit_profile.html', form=form)


@backstage_bp.route('/settings/change-username', methods=['GET', 'POST'])
@login_required
@fresh_login_required
def change_username():
    form = ChangeUsernameForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        db.session.commit()

        content = render_template('logs/settings/change_username.txt')
        log_user(content)

        flash(_('Username updated.'), 'success')
        return redirect_back()

    return render_template('backstage/settings/change_username.html', form=form)


@backstage_bp.route('/settings/change-password', methods=['GET', 'POST'])
@fresh_login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        content = render_template('logs/settings/change_password.txt')
        log_user(content)

        if current_user.validate_password(form.old_password.data):
            current_user.set_password(form.password.data)
            db.session.commit()

            flash(_('Password updated.'), 'success')
            return redirect_back()
        else:
            flash(_('Old password is incorrect.'), 'warning')

    return render_template('backstage/settings/change_password.html', form=form)


@backstage_bp.route('/solution/<path:filename>')
@login_required
def get_solution(filename):
    content = render_template('logs/download.txt')
    log_user(content)

    if Competition.is_start():
        path = os.path.join(
            current_app.config['SOLUTION_SAVE_PATH'], filename)
        if os.path.exists(path):
            return send_file(path, as_attachment=True)
        else:
            abort(404)
    else:
        abort(403)

MMCs/blueprints/teacher.py
# -*- coding: utf-8 -*-

from flask import Blueprint, current_app, flash, render_template, request
from flask_babel import _
from flask_login import current_user, login_required

from MMCs.decorators import teacher_required
from MMCs.extensions import db
from MMCs.forms import ChangeScoreForm
from MMCs.models import Competition, Task, Solution
from MMCs.utils import flash_errors, log_user, redirect_back

teacher_bp = Blueprint('teacher', __name__)


@teacher_bp.route('/')
@teacher_required
@login_required
def index():
    com = Competition.current_competition()
    if com and com.is_start():
        task_all = Task.query.filter(
            Task.competition_id == com.id,
            Task.teacher_id == current_user.id).count()

        task_finished = 0
        if task_all:
            task_finished = Task.query.filter(
                Task.competition_id == com.id,
                Task.teacher_id == current_user.id,
                Task.score != None).count()

        return render_template(
            'backstage/teacher/overview.html', task_finished=task_finished, task_all=task_all)

    return render_template('backstage/teacher/overview.html')


@teacher_bp.route('/task')
@teacher_required
@login_required
def manage_task():
    com = Competition.current_competition()
    if com:
        page = request.args.get('page', 1, type=int)
        form = ChangeScoreForm()

        pagination = Task.query.filter(
            Task.competition_id == com.id,
            Task.teacher_id == current_user.id
        ).join(Solution).order_by(Solution.name).paginate(page, current_app.config['SOLUTION_PER_PAGE'])

        return render_template(
            'backstage/teacher/manage_task.html',
            pagination=pagination, page=page, form=form)

    return render_template('backstage/teacher/manage_task.html')


@teacher_bp.route('/task/change/<int:task_id>', methods=['POST'])
@teacher_required
@login_required
def change(task_id):
    form = ChangeScoreForm()
    upper = current_app.config['SCORE_UPPER_LIMIT']
    lower = current_app.config['SCORE_LOWER_LIMIT']
    if form.validate_on_submit:
        content = render_template('logs/teacher/update.txt')
        log_user(content)

        if form.score.data:
            if lower <= form.score.data <= upper:
                task = Task.query.get_or_404(task_id)
                task.score = form.score.data
                task.remark = form.remark.data
                db.session.commit()

                flash(_('Score Updated.'), 'success')
            else:
                flash(_(
                    'Score out of range from %(lower)s to %(upper)s.', lower=lower, upper=upper), 'warning')
        else:
            flash(_('Invalid score.'), 'warning')

    flash_errors(form)
    return redirect_back()

MMCs/templates/backstage/admin/manage_task/add.html
{% extends 'backstage/admin/manage_task/base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block task_content %}
    {% if is_start() %}
        <div class="table-responsive">
            <table class="table table-striped table-hover table-sm">
                <thead>
                <tr class="text-center">
                    <th>#</th>
                    <th>{{ _('Team number') }}</th>
                    <th>{{ _('Problem') }}</th>
                    <th>{{ _('UUID') }}</th>
                    <th>{{ _('Actions') }}</th>
                </tr>
                </thead>
                {% for solution in pagination.items %}
                    <tr>
                        <td class="text-center">{{ config['SOLUTION_PER_PAGE']*(page-1) + loop.index }}</td>
                        <td class="text-center">
                            <span class="badge badge-pill badge-info">
                                {{ solution.team_number }}
                            </span>
                        </td>
                        <td class="text-center">
                            <span class="badge badge-pill badge-primary">
                                {{ solution.problem }}
                            </span>
                        </td>
                        <td class="text-center">
                            <a href="{{ url_for('backstage.get_solution', filename=solution.uuid) }}"
                               target="_blank">
                                {{ solution.uuid }}
                            </a>
                        </td>
                        <td class="text-center">
                            <form role="form"
                                  action="{{ url_for('admin.task_add', user_id=user_id, solution_id=solution.id) }}"
                                  method="post">
                                <input type="hidden" id="csrf_token" name="csrf_token" value="{{ csrf_token() }}"/>
                                <button class="btn btn-info btn-sm">
                                    <span class="oi oi-plus"></span> {{ _("Add") }}
                                </button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="page-footer">
            {{ render_pagination(pagination) }}
        </div>
    {% else %}
        {% include "backstage/tips/no_start.html" %}
    {% endif %}
{% endblock %}

MMCs/templates/backstage/admin/manage_task/base.html
{% extends 'backstage/admin/base.html' %}

{% block title %}Task{% endblock %}

{% block setting_content %}
    <div class="card w-100">
        <div class="card-header">
            <div class="nav nav-tabs card-header-tabs" role="tablist">
                {{ render_nav_item("admin.method", _("Method")) }}
                {{ render_nav_item("admin.teacher_view", _("Teacher View")) }}
                {{ render_nav_item("admin.solution_view", _("Solution View")) }}
                {% if request.endpoint and request.endpoint == "admin.check_user" %}
                    <a class="nav-link active">
                        {{ _('Check') }}
                    </a>
                {% endif %}
                {% if request.endpoint and request.endpoint == "admin.task_add_list" %}
                    <a class="nav-link active">
                        {{ _('Add') }}
                    </a>
                {% endif %}
            </div>
        </div>
        <div class="card-body">
            {% block task_content %}
            {% endblock %}
        </div>
    </div>
{% endblock %}

MMCs/templates/backstage/admin/manage_task/check.html
{% extends 'backstage/admin/manage_task/base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block task_content %}
    {% if is_start() %}
        <div class="table-responsive">
            <table class="table table-striped table-hover table-sm">
                <thead>
                <tr class="text-center">
                    <th>#</th>
                    <th>{{ _('Team number') }}</th>
                    <th>{{ _('Problem') }}</th>
                    <th>{{ _('Score') }}</th>
                    <th>{{ _('Remark') }}</th>
                    <th>{{ _('Actions') }}</th>
                </tr>
                </thead>
                {% for task in pagination.items %}
                    <tr>
                        <td class="text-center">
                            {{ pagination.total - (config['SOLUTION_PER_PAGE']*(page-1) + loop.index) + 1 }}
                        </td>
                        <td class="text-center">
                            <span class="badge badge-pill badge-info">
                                {{ task.team_number }}
                            </span>
                        </td>
                        <td class="text-center">
                <span class="badge badge-pill badge-primary">
                    {{ task.problem }}
                </span>
                        </td>
                        <td class="text-center">{{ task.score }}</td>
                        <td class="text-center">{{ task.remark }}</td>
                        <td class="text-center">
                            <button class="btn btn-danger btn-sm" data-toggle="modal" data-target="#confirm-delete"
                                    data-href="{{ url_for('admin.method_delete_task', task_id=task.id) }}">
                                <span class="oi oi-trash" aria-hidden="true"></span> {{ _('Delete') }}
                            </button>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="page-footer">
            {{ render_pagination(pagination) }}
        </div>
    {% else %}
        {% include "backstage/tips/no_start.html" %}
    {% endif %}

    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="confirmModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmModalLabel">
                        {{ _('Delete Confirm') }}
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span class="oi oi-delete"></span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>{{ _('Are you sure you want to delete this item?') }}</p>
                </div>
                <div class="modal-footer">
                    <form class="delete-form" method="post">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                        <button type="button" class="btn btn-default" data-dismiss="modal">
                            <span class="oi oi-action-undo"></span> {{ _('Cancel') }}
                        </button>
                        <button class="btn btn-danger btn-confirm" type="submit">
                            <span class="oi oi-trash"></span> {{ _('Delete') }}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

MMCs/templates/backstage/admin/manage_task/method.html
{% extends 'backstage/admin/manage_task/base.html' %}

{% block task_content %}
    {% if is_start() %}
        <div class="btn-group btn-group-vertical btn-block" role="group">
            <a class="btn btn-danger text-white" data-toggle="modal" data-target="#confirm-random"
               data-href="{{ url_for('admin.method_random') }}">
                <span class="oi oi-random"></span> {{ _('Random') }}</a>
            <a class="btn btn-primary text-white" href="{{ url_for('admin.teacher_view') }}">
                <span class="oi oi-pencil"></span> {{ _('Manual') }}</a>
        </div>
    {% else %}
        {% include "backstage/tips/no_start.html" %}
    {% endif %}

    <!-- random confirm model -->
    <div class="modal fade" id="confirm-random" tabindex="-1" role="dialog" aria-labelledby="confirmModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmModalLabel">{{ _('Random Confirm') }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span class="oi oi-delete"></span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>{{ _('Are you sure you want to randomly assign?') }}</p>
                    <p>{{ _('If there were assigned, data will be deleted.') }}</p>
                </div>
                <div class="modal-footer">
                    <form class="random-form" method="post">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        <button type="button" class="btn btn-default" data-dismiss="modal">
                            <span class="oi oi-action-undo"></span> {{ _('Cancel') }}
                        </button>
                        <button class="btn btn-danger btn-confirm" type="submit">
                            <span class="oi oi-check"></span> {{ _('Confirm') }}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

MMCs/templates/backstage/admin/manage_task/teacher_view.html
{% extends 'backstage/admin/manage_task/base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block task_content %}
    {% if is_start() %}
        <div class="table-responsive">
            <table class="table table-striped table-hover table-sm">
                <thead>
                <tr class="text-center">
                    <th>#</th>
                    <th>{{ _('Username') }}</th>
                    <th>{{ _('Realname') }}</th>
                    <th>{{ _('Tasks') }}</th>
                    <th>{{ _('Finished') }}</th>
                    <th>{{ _('Actions') }}</th>
                </tr>
                </thead>
                {% for user in pagination.items %}
                    <tr>
                        <td class="text-center">{{ config['USER_PER_PAGE']*(page-1) + loop.index }}</td>
                        <td class="text-center">{{ user.username }}</td>
                        <td class="text-center">{{ user.realname }}</td>
                        <td class="text-center">
                            <span class="badge badge-pill badge-secondary">
                                {{ user.current_all_tasks|length }}
                            </span>
                        </td>
                        <td class="text-center">
                            <span class="badge badge-pill badge-success">
                                {{ user.current_finished_task|length }}
                            </span>
                        </td>
                        <td class="text-center">
                            {% if not user.is_root %}
                                <div class="dropdown">
                                    <button class="btn btn-sm btn-info dropdown-toggle" type="button"
                                            id="dropdownMenuButton"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <span class="oi oi-cog"></span> {{ _("Edit") }}
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <form method="post" action="{{ url_for('admin.check_user', user_id=user.id) }}">
                                            {{ check_form.csrf_token }}
                                            {{ check_form.submit(class="dropdown-item") }}
                                        </form>
                                        <form method="post" action="{{ url_for('admin.task_add_list', user_id=user.id) }}">
                                            {{ add_form.csrf_token }}
                                            {{ add_form.submit(class="dropdown-item") }}
                                        </form>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item badge-danger" data-toggle="modal"
                                           data-target="#confirm-delete"
                                           data-href="{{ url_for('admin.delete_user_task', user_id=user.id) }}">
                                            <span class="oi oi-trash" aria-hidden="true"></span> {{ _('Delete') }}
                                        </a>
                                    </div>
                                </div>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </table>
            <div class="page-footer">
                {{ render_pagination(pagination) }}
            </div>
        </div>
    {% else %}
        {% include "backstage/tips/no_start.html" %}
    {% endif %}

    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="confirmModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmModalLabel">
                        {{ _('Delete Confirm') }}
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span class="oi oi-delete"></span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>{{ _('Are you sure you want to delete this item?') }}</p>
                </div>
                <div class="modal-footer">
                    <form class="delete-form" method="post">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                        <button type="button" class="btn btn-default" data-dismiss="modal">
                            <span class="oi oi-action-undo"></span> {{ _('Cancel') }}
                        </button>
                        <button class="btn btn-danger btn-confirm" type="submit">
                            <span class="oi oi-trash"></span> {{ _('Delete') }}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}