MMCs/blueprints/auth.py
# -*- coding: utf-8 -*-

from flask import Blueprint, flash, redirect, render_template, url_for
from flask_babel import _
from flask_login import (confirm_login, current_user, login_fresh,
                         login_required, login_user, logout_user)

from MMCs.forms import LoginForm
from MMCs.models import User
from MMCs.utils import log_user, redirect_back

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('front.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.validate_password(form.password.data):
            if login_user(user, form.remember_me.data):
                content = render_template('logs/auth/login.txt')
                log_user(content)

                flash(_('Login success.'), 'info')
                return redirect_back()
        else:
            flash(_('Invalid username or password.'), 'warning')

    return render_template('auth/login.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    content = render_template('logs/auth/logout.txt')
    log_user(content)

    logout_user()
    flash(_('Logout success.'), 'info')

    return redirect(url_for('front.index'))


@auth_bp.route('/re-authenticate', methods=['GET', 'POST'])
@login_required
def re_authenticate():
    if login_fresh():
        return redirect(url_for('front.index'))

    form = LoginForm()
    if form.validate_on_submit() and current_user.validate_password(form.password.data):
        confirm_login()

        content = render_template('logs/auth/login.txt')
        log_user(content)

        return redirect_back()
    return render_template('auth/login.html', form=form)

MMCs/blueprints/backstage.py
# -*- coding: utf-8 -*-

import os

from flask import (Blueprint, abort, current_app, flash, render_template,
                   send_file)
from flask_babel import _
from flask_login import current_user, fresh_login_required, login_required

from MMCs.extensions import db
from MMCs.forms import ChangePasswordForm, ChangeUsernameForm, EditProfileForm
from MMCs.models import Competition
from MMCs.utils import log_user, redirect_back

backstage_bp = Blueprint('backstage', __name__)


@backstage_bp.route('/settings/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.realname = form.realname.data
        current_user.remark = form.remark.data
        db.session.commit()

        content = render_template('logs/settings/edit_profile.txt')
        log_user(content)

        flash(_('Profile updated.'), 'success')
        return redirect_back()

    form.realname.data = current_user.realname
    form.remark.data = current_user.remark

    return render_template('backstage/settings/edit_profile.html', form=form)


@backstage_bp.route('/settings/change-username', methods=['GET', 'POST'])
@login_required
@fresh_login_required
def change_username():
    form = ChangeUsernameForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        db.session.commit()

        content = render_template('logs/settings/change_username.txt')
        log_user(content)

        flash(_('Username updated.'), 'success')
        return redirect_back()

    return render_template('backstage/settings/change_username.html', form=form)


@backstage_bp.route('/settings/change-password', methods=['GET', 'POST'])
@fresh_login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        content = render_template('logs/settings/change_password.txt')
        log_user(content)

        if current_user.validate_password(form.old_password.data):
            current_user.set_password(form.password.data)
            db.session.commit()

            flash(_('Password updated.'), 'success')
            return redirect_back()
        else:
            flash(_('Old password is incorrect.'), 'warning')

    return render_template('backstage/settings/change_password.html', form=form)


@backstage_bp.route('/solution/<path:filename>')
@login_required
def get_solution(filename):
    content = render_template('logs/download.txt')
    log_user(content)

    if Competition.is_start():
        path = os.path.join(
            current_app.config['SOLUTION_SAVE_PATH'], filename)
        if os.path.exists(path):
            return send_file(path, as_attachment=True)
        else:
            abort(404)
    else:
        abort(403)

MMCs/blueprints/front.py
# -*- coding: utf-8 -*-

from flask import (Blueprint, abort, current_app, flash, make_response,
                   redirect, render_template, url_for)
from flask_babel import _
from flask_login import current_user

from MMCs.extensions import cache, db
from MMCs.utils import redirect_back

front_bp = Blueprint('front', __name__)


@front_bp.route('/')
def index():
    if current_user.is_authenticated:
        if current_user.is_root:
            return redirect(url_for('root.index'))
        elif current_user.is_admin:
            return redirect(url_for('admin.index'))
        elif current_user.is_teacher:
            return redirect(url_for('teacher.index'))
    return render_template('front/index.html')


@front_bp.route('/about')
@cache.cached(timeout=10)
def about():
    return render_template('front/about.html')


@front_bp.route('/set-locale/<locale>')
def set_locale(locale):
    if locale not in current_app.config['MMCS_LOCALES']:
        abort(404)

    response = make_response(redirect_back())
    response.set_cookie('locale', locale, max_age=60 * 60 * 24 * 30)

    if current_user.is_authenticated:
        current_user.locale = locale
        db.session.commit()

    flash(_('Setting updated.'), 'success')

    return response

MMCs/blueprints/root.py
# -*- coding: utf-8 -*-

import os
from uuid import uuid4

from flask import (Blueprint, current_app, flash, redirect, render_template,
                   request, send_file, url_for)
from flask_babel import _
from flask_login import fresh_login_required, login_required

from MMCs.decorators import root_required
from MMCs.extensions import db
from MMCs.forms import (AboutEditForm, AboutImageUploadForm,
                        ChangeUsernameForm, CompetitionNameForm,
                        CompetitionSettingForm, DownloadLogForm,
                        EditProfileForm, ErrorImageUploadForm,
                        IndexImageUploadForm, NoticeEditForm, RegisterForm,
                        RootChangePasswordForm)
from MMCs.models import Competition, User
from MMCs.settings import basedir
from MMCs.utils import (download_solution_score, download_teacher_result,
                        download_user_operation, flash_errors, log_user,
                        read_localfile, redirect_back, write_localfile,
                        zip2here)

root_bp = Blueprint('root', __name__)


@root_bp.route('/')
@root_required
@login_required
def index():
    return redirect(url_for('.manage_competition'))


@root_bp.route('/competition')
@root_required
@login_required
def manage_competition():
    return redirect(url_for('root.behavior'))


@root_bp.route('/competition/behavior')
@root_required
@login_required
def behavior():
    form = CompetitionNameForm()
    return render_template(
        'backstage/root/manage_competition/behavior.html', form=form)


@root_bp.route('/competition/history')
@root_required
@login_required
def history():
    page = request.args.get('page', 1, type=int)
    pagination = Competition.query.order_by(
        Competition.id.desc()).paginate(page, current_app.config['COMPETITION_PER_PAGE'])

    return render_template(
        'backstage/root/manage_competition/history.html',
        pagination=pagination, page=page)


@root_bp.route('/competition/notice', methods=['GET', 'POST'])
@fresh_login_required
@root_required
@login_required
def notice():
    form = NoticeEditForm()
    path = os.path.join(
        basedir, current_app.name, current_app.template_folder, 'showing/notice.html')
    if form.validate_on_submit():
        content = render_template('logs/root/competition/notice.txt')
        log_user(content)

        write_localfile(path, form.notice.data)
        flash(_('Setting updated.'), 'success')
        return redirect_back()
    form.notice.data = read_localfile(path)

    return render_template(
        'backstage/root/manage_competition/notice.html', form=form)


@root_bp.route('/competition/settings', methods=['GET', 'POST'])
@fresh_login_required
@root_required
@login_required
def competition_settings():
    form = CompetitionSettingForm()
    if form.validate_on_submit():
        content = render_template('logs/root/competition/setting.txt')
        log_user(content)

        current_app.config['SOLUTION_TASK_NUMBER'] = form.solution_task_number.data
        current_app.config['USER_PER_PAGE'] = form.user_per_page.data
        current_app.config['SOLUTION_PER_PAGE'] = form.solution_per_page.data
        current_app.config['COMPETITION_PER_PAGE'] = form.competition_per_page.data
        current_app.config['DROPZONE_MAX_FILES'] = form.dropzone_max_files.data

    form.solution_task_number.data = current_app.config['SOLUTION_TASK_NUMBER']
    form.user_per_page.data = current_app.config['USER_PER_PAGE']
    form.solution_per_page.data = current_app.config['SOLUTION_PER_PAGE']
    form.competition_per_page.data = current_app.config['COMPETITION_PER_PAGE']
    form.dropzone_max_files.data = current_app.config['DROPZONE_MAX_FILES']

    return render_template(
        'backstage/root/manage_competition/notice.html', form=form)


@root_bp.route('/competition/behavior/start', methods=['POST'])
@fresh_login_required
@root_required
@login_required
def start_competition():
    form = CompetitionNameForm()
    if form.validate_on_submit():
        content = render_template('logs/root/competition/start.txt')
        log_user(content)

        com = Competition(name=form.name.data, flag=True)
        db.session.add(com)
        db.session.commit()
        flash(_('A new competition start now.'), 'success')

    flash_errors(form)

    return redirect_back()


@root_bp.route('/competition/behavior/switch', methods=['POST'])
@fresh_login_required
@root_required
@login_required
def switch_state():
    com = Competition.current_competition()
    if com:
        if com.is_start():
            com.flag = False
            db.session.commit()

            content = render_template('logs/root/competition/stop.txt')
            log_user(content)

            flash(_('Competition stopped.'), 'success')
        else:
            com.flag = True
            db.session.commit()

            content = render_template('logs/root/competition/start.txt')
            log_user(content)

            flash(_('Competition continued.'), 'success')
    else:
        flash(_('Please start new competition before do it.'), 'warning')

    return redirect_back()


@root_bp.route('/personnel')
@root_required
@login_required
def manage_personnel():
    return redirect(url_for('.personnel_list'))


@root_bp.route('/personnel/list')
@root_required
@login_required
def personnel_list():
    page = request.args.get('page', 1, type=int)
    pagination = User.query.order_by(
        User.id.desc()).paginate(page, current_app.config['USER_PER_PAGE'])

    return render_template(
        'backstage/root/manage_personnel/personnel_list.html',
        pagination=pagination, page=page)


@root_bp.route('/personnel/list/change-password/<int:user_id>', methods=['GET', 'POST'])
@fresh_login_required
@root_required
@login_required
def change_password(user_id):
    form = RootChangePasswordForm()
    if form.validate_on_submit():
        content = render_template('logs/root/personnel/change_password.txt')
        log_user(content)

        user = User.query.get_or_404(user_id)
        user.set_password(form.password.data)
        db.session.commit()

        flash(_('Password updated.'), 'success')
        return redirect(url_for('.personnel_list'))

    return render_template(
        'backstage/root/manage_personnel/personnel_edit.html', form=form)


@root_bp.route('/personnel/list/edit-profile/<int:user_id>', methods=['GET', 'POST'])
@fresh_login_required
@root_required
@login_required
def edit_profile(user_id):
    user = User.query.get_or_404(user_id)
    form = EditProfileForm()
    if form.validate_on_submit():
        content = render_template('logs/root/personnel/edit.txt')
        log_user(content)

        user.realname = form.realname.data
        user.remark = form.remark.data
        db.session.commit()

        flash(_('Profile updated.'), 'success')
        return redirect(url_for('.personnel_list'))

    form.realname.data = user.realname
    form.remark.data = user.remark

    return render_template(
        'backstage/root/manage_personnel/personnel_edit.html', form=form)


@root_bp.route('/personnel/list/change-username/<int:user_id>', methods=['GET', 'POST'])
@fresh_login_required
@root_required
@login_required
def change_username(user_id):
    user = User.query.get_or_404(user_id)
    form = ChangeUsernameForm()
    if form.validate_on_submit():
        content = render_template('logs/root/personnel/change_username.txt')
        log_user(content)

        user.username = form.username.data
        db.session.commit()

        flash(_('Username updated.'), 'success')
        return redirect(url_for('.personnel_list'))

    form.username.data = user.username
    form.username2.data = user.username

    return render_template(
        'backstage/root/manage_personnel/personnel_edit.html', form=form)


@root_bp.route('/personnel/register', methods=['GET', 'POST'])
@fresh_login_required
@root_required
@login_required
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        content = render_template('logs/root/personnel/register.txt')
        log_user(content)

        user = User(
            username=form.username.data,
            realname=form.realname.data,
            permission=form.permission.data,
            remark=form.remark.data
        )
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash(_('Account registered.'), 'success')
        return redirect_back()

    return render_template('backstage/root/manage_personnel/register.html', form=form)


@root_bp.route('/delete/user/<int:user_id>', methods=['POST'])
@fresh_login_required
@root_required
@login_required
def delete_user(user_id):
    content = render_template('logs/root/personnel/delete.txt')
    log_user(content)

    user = User.query.get_or_404(user_id)
    db.session.delete(user)
    db.session.commit()

    flash(_('User deleted.'), 'info')
    return redirect_back()


@root_bp.route('/score/download/<int:competition_id>/teacher', methods=['POST'])
@fresh_login_required
@root_required
@login_required
def download_teacher(competition_id):
    content = render_template('logs/root/competition/history.txt')
    log_user(content)

    com = Competition.query.get_or_404(competition_id)
    if com.tasks:
        zfile = download_teacher_result(competition_id)

        flash(_('The result file is already downloaded.'), 'success')
        return send_file(zfile, as_attachment=True)
    else:
        flash(_('No task.'), 'warning')
        return redirect_back()


@root_bp.route('/score/download/<int:competition_id>/result', methods=['POST'])
@fresh_login_required
@root_required
@login_required
def download_result(competition_id):
    content = render_template('logs/root/competition/history.txt')
    log_user(content)

    com = Competition.query.get_or_404(competition_id)
    if com.solutions:
        zfile = download_solution_score(competition_id)

MMCs/templates/backstage/base.html
{% extends 'base.html' %}
{% from 'macros.html' import render_nav_item %}

{% block title %}Dashboard{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('front.index') }}">
                <img src="{{ url_for('static', filename='navbar-brand.ico') }}" alt="MMCs" width="80">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="navbar-nav ml-auto">
                    {{ render_nav_item('front.index', _('Dashboard'), "oi oi-dashboard") }}
                    <a class="nav-item nav-link" data-toggle="modal" data-target="#aboutModal">
                        <span class="oi oi-info"></span> {{ _('Notice') }}</a>
                    <div class="dropdown nav-item">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                            <span class="oi oi-wrench"></span> {{ _('Manage') }}
                        </a>
                        <div class="dropdown-menu" role="menu">
                            {% if current_user.is_root %}
                                <a class="dropdown-item"
                                   href="{{ url_for('root.index') }}">{{ _('Overview') }}</a>
                                <a class="dropdown-item"
                                   href="{{ url_for('root.manage_competition') }}">{{ _('Competition Management') }}</a>
                                <a class="dropdown-item"
                                   href="{{ url_for('root.manage_personnel') }}">{{ _('Personnel Management') }}</a>
                            {% elif current_user.is_admin %}
                                <a class="dropdown-item"
                                   href="{{ url_for('admin.index') }}">{{ _('Overview') }}</a>
                                <a class="dropdown-item"
                                   href="{{ url_for('admin.manage_solution') }}">{{ _('Solution Management') }}</a>
                                <a class="dropdown-item"
                                   href="{{ url_for('admin.manage_task') }}">{{ _('Task Management') }}</a>
                                <a class="dropdown-item"
                                   href="{{ url_for('admin.manage_score') }}">{{ _('Score Management') }}</a>
                            {% elif current_user.is_teacher %}
                                <a class="dropdown-item"
                                   href="{{ url_for('teacher.index') }}">{{ _('Overview') }}</a>
                                <a class="dropdown-item"
                                   href="{{ url_for('teacher.manage_task') }}">{{ _('Task Management') }}</a>
                            {% endif %}
                        </div>
                    </div>
                    <div class="dropdown nav-item">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown">
                            <span class="oi oi-globe"></span> {{ _('Language') }}
                        </a>
                        <div class="dropdown-menu" role="menu">
                            <a class="dropdown-item"
                               href="{{ url_for('front.set_locale', locale='zh_Hans_CN') }}">简体中文</a>
                            <a class="dropdown-item"
                               href="{{ url_for('front.set_locale', locale='en_US') }}">English</a>
                        </div>
                    </div>
                    <div class="dropdown nav-item">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown">
                            <span class="oi oi-person"></span>
                        </a>
                        <div class="dropdown-menu" role="menu">
                            <h6 class="dropdown-header">{{ _('Logged in as') }} {{ current_user.realname }}</h6>
                            <a class="dropdown-item" href="{{ url_for('backstage.edit_profile') }}">
                                <span class="oi oi-cog"></span> {{ _('Settings') }}</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item"
                               href="{{ url_for('auth.logout', next=request.full_path) }}">
                                <span class="oi oi-account-logout"></span> {{ _('Logout') }}</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <!-- notice modal -->
    <div class="modal fade" id="aboutModal" tabindex="-1" role="dialog" aria-labelledby="aboutModalTitle"
         aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="aboutModalTitle">{{ _('Notice') }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        <span class="oi oi-delete"></span>
                    </button>
                </div>
                <div class="modal-body">
                    {{ render_text("showing/notice.html")|safe }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">
                        {{ _('Close') }}
                    </button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}